version: '3.8'

services:
  # MongoDB Service
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--noauth"]
    environment:
      - MONGO_INITDB_DATABASE=db

  # Backend Service (Node.js with Mongoose)
  backend:
    image: backend
    container_name: backend
    working_dir: /app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expose backend port
    volumes:
    - ./src:/app/src 
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=${NODE_ENV}
      - PORT=3000
      - HOST=0.0.0.0
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - LINK_HOST=${LINK_HOST}
      - LINK_PORT=${LINK_PORT}

  # Frontend Service (Vue.js)
  frontend:
    image: frontend
    container_name: frontend
    working_dir: /app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src 
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_APP_API_URL=${VITE_APP_API_URL}

volumes:
  mongo_data: # This will create a volume for MongoDB data persistence
