version: '3.8'

services:
  # MongoDB Service
  mongo:
    image: mongo:latest
    container_name: mongo_db
    env_file:
      - ./.env.docker 
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Backend Service (Node.js with Mongoose)
  backend:
    image: linkext_backend
    container_name: backend
    working_dir: /app
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.docker
    ports:
      - "3000:3000" # Expose backend port
    depends_on:
      - mongo
    volumes:
      - ./backend:/app

  # Frontend Service (Vue.js)
  frontend:
    image: linkext_frontend
    container_name: frontend
    working_dir: /app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env.local
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  mongo_data: # This will create a volume for MongoDB data persistence
