version: '3.8'

services:
  # Nginx Service
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/key.pem:/root/ssl/key.pem
      - ./nginx/cert.pem:/root/ssl/cert.pem
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  # MongoDB Service
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--noauth"]
    environment:
      - MONGO_INITDB_DATABASE=db
    restart: unless-stopped

  # Backend Service (Node.js with Mongoose)
  backend:
    image: backend
    container_name: backend
    working_dir: /app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expose backend port
    volumes:
    - ./src:/app/src 
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    restart: unless-stopped

  # Frontend Service (Vue.js)
  frontend:
    image: frontend
    container_name: frontend
    working_dir: /app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src 
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    restart: unless-stopped

volumes:
  mongo_data: # This will create a volume for MongoDB data persistence
